AWSTemplateFormatVersion: "2010-09-09"

Description: AWS Bill Export Solution

Parameters:
    AuthorizationType:
        Type: String
        Description: Type of auhtorization to use for the API Gateway
        AllowedValues:
          - AWS_IAM
          - NONE
        Default: NONE

Conditions:
    IamAuthorization: !Equals [!Ref AuthorizationType, AWS_IAM]

Mappings:
    RegionMap:
        us-east-1:
            bucketname: vinhngo1999-us-east-1
        us-east-2:
            bucketname: vinhngo1999-us-east-2
        us-west-1:
            bucketname: vinhngo1999-us-west-1
        us-west-2:
            bucketname: vinhngo1999-us-west-2
        ap-south-1:
            bucketname: vinhngo1999-ap-south-1
        ap-northeast-2:
            bucketname: vinhngo1999-ap-northeast-2
        ap-southeast-1:
            bucketname: vinhngo1999-ap-southeast-1
        ap-southeast-2:
            bucketname: vinhngo1999-ap-southeast-2
        ap-northeast-1:
            bucketname: vinhngo1999-ap-northeast-1
        ca-central-1:
            bucketname: vinhngo1999-ca-central-1
        eu-central-1:
            bucketname: vinhngo1999-eu-central-1
        eu-west-1:
            bucketname: vinhngo1999-eu-west-1
        eu-west-2:
            bucketname: vinhngo1999-eu-west-2
        eu-west-3:
            bucketname: vinhngo1999-eu-west-3
        eu-north-1:
            bucketname: vinhngo1999-eu-north-1
        sa-east-1:
            bucketname: vinhngo1999-sa-east-1

Resources:

    LambdaAPIGatewayPermission:
        Type: AWS::Lambda::Permission
        Properties:
            FunctionName: !Ref LambdaFunction
            Action: lambda:InvokeFunction
            Principal: apigateway.amazonaws.com
            SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*/*"

    LambdaLogGroup:
        Type: AWS::Logs::LogGroup
        Properties:
            LogGroupName: /aws/lambda/BillRetriever
            RetentionInDays: 14

    LambdaFunction:
        DependsOn:
          - LambdaLogGroup
        Type: AWS::Lambda::Function
        Properties:
            FunctionName: BillRetriever
            Code:
                S3Bucket:
                    Fn::FindInMap:
                      - RegionMap
                      - !Ref 'AWS::Region'
                      - bucketname
                S3Key: 'billretriever/app.zip'
            Handler: index.handler
            Role: !GetAtt LambdaExecutionRole.Arn
            Environment:
                Variables:
                    ACCOUNTID: !Ref AWS::AccountId
            Runtime: nodejs18.x
            MemorySize: 1024
            Timeout: 30  # maximum for http api is 30s
    
    LambdaExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Principal:
                        Service:
                          - lambda.amazonaws.com
                    Action:
                      - sts:AssumeRole
            Path: /
            ManagedPolicyArns:
              - arn:aws:iam::aws:policy/job-function/Billing
            Policies:
              - PolicyName: root
                PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                      - Effect: Allow
                        Action:
                          - logs:CreateLogGroup
                          - logs:CreateLogStream
                          - logs:PutLogEvents
                        Resource: arn:aws:logs:*:*:*
    
    HttpApi:
        Type: AWS::ApiGatewayV2::Api
        Properties:
            Name: !Ref AWS::StackName
            ProtocolType: HTTP
            RouteSelectionExpression: "$request.method $request.path"
            Version: "1.0"
            CorsConfiguration:
                AllowMethods:
                  - GET
                AllowOrigins:
                  - "*"

    HttpApiStage:
        Type: AWS::ApiGatewayV2::Stage
        Properties:
            ApiId: !Ref HttpApi
            AutoDeploy: true
            StageName: "$default"

    HttpApiGetCompletebillRoute:
        Type: AWS::ApiGatewayV2::Route
        Properties:
            ApiId: !Ref HttpApi
            AuthorizationType: !Ref AuthorizationType
            RouteKey: "GET /completebill.json"
            Target: !Sub "integrations/${HttpApiIntegration}"

    HttpApiGetInvoicelistRoute:
        Type: AWS::ApiGatewayV2::Route
        Properties:
            ApiId: !Ref HttpApi
            AuthorizationType: !Ref AuthorizationType
            RouteKey: "GET /invoicelist.json"
            Target: !Sub "integrations/${HttpApiIntegration}"

    HttpApiGetLinkedaccountbillsummaryRoute:
        Type: AWS::ApiGatewayV2::Route
        Properties:
            ApiId: !Ref HttpApi
            AuthorizationType: !Ref AuthorizationType
            RouteKey: "GET /linkedaccountbillsummary.json"
            Target: !Sub "integrations/${HttpApiIntegration}"

    HttpApiGetGenerateRoute:
        Type: AWS::ApiGatewayV2::Route
        Properties:
            ApiId: !Ref HttpApi
            AuthorizationType: !Ref AuthorizationType
            RouteKey: "GET /generate.json"
            Target: !Sub "integrations/${HttpApiIntegration}"

    HttpApiGetDownloadRoute:
        Type: AWS::ApiGatewayV2::Route
        Properties:
            ApiId: !Ref HttpApi
            AuthorizationType: !Ref AuthorizationType
            RouteKey: "GET /download.pdf"
            Target: !Sub "integrations/${HttpApiIntegration}"


    HttpApiIntegration:
        Type: AWS::ApiGatewayV2::Integration
        Properties:
            ApiId: !Ref HttpApi
            ConnectionType: INTERNET
            IntegrationMethod: POST
            IntegrationType: AWS_PROXY
            IntegrationUri: !GetAtt LambdaFunction.Arn
            PayloadFormatVersion: "2.0"

    HttpApiInvokePolicy:
        Type: AWS::IAM::ManagedPolicy
        Condition: IamAuthorization
        Properties:
            Description: !Sub "Allows usage of the HttpApi in ${AWS::StackName}"
            PolicyDocument:
                Version: 2012-10-17
                Statement:
                    Effect: Allow
                    Action: execute-api:Invoke
                    Resource: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/${HttpApiStage}/GET/*"

Outputs:

    Url:
        Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
    HttpApiInvokePolicy:
        Value: !If
            - IamAuthorization
            - !Ref HttpApiInvokePolicy
            - ""